"""phase2_exercise_attempts

Revision ID: 2e532d3dd383
Revises: b7e2a9c4d1f0
Create Date: 2026-07-30 20:46:41.385952
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2e532d3dd383"
down_revision: Union[str, Sequence[str], None] = "b7e2a9c4d1f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercise_attempts",
        sa.Column(
            "visitor_id", sa.String(length=64), nullable=False, comment="访客 ID"
        ),
        sa.Column(
            "request_id",
            sa.String(length=64),
            nullable=False,
            comment="前端执行请求 ID（幂等键）",
        ),
        sa.Column(
            "lesson_slug", sa.String(length=128), nullable=False, comment="课程 slug"
        ),
        sa.Column(
            "exercise_id", sa.String(length=128), nullable=False, comment="练习 ID"
        ),
        sa.Column(
            "execution_id",
            sa.String(length=64),
            nullable=True,
            comment="Runner 返回的 execution ID",
        ),
        sa.Column("source", sa.String(length=32), nullable=False, comment="来源"),
        sa.Column("language", sa.String(length=16), nullable=False, comment="代码语言"),
        sa.Column("code", sa.Text(), nullable=False, comment="提交的代码"),
        sa.Column(
            "execution_status",
            sa.String(length=20),
            nullable=False,
            comment="执行状态: success / error / timeout / rejected / unavailable",
        ),
        sa.Column(
            "verification_status",
            sa.String(length=20),
            nullable=False,
            comment="验证状态: not_run / passed / failed / unverifiable",
        ),
        sa.Column(
            "failure_reason",
            sa.Text(),
            nullable=True,
            comment="失败原因（仅 failed/unverifiable）",
        ),
        sa.Column("stdout", sa.Text(), nullable=True, comment="标准输出"),
        sa.Column("stderr", sa.Text(), nullable=True, comment="标准错误"),
        sa.Column(
            "duration_ms", sa.Integer(), nullable=True, comment="执行耗时（毫秒）"
        ),
        sa.Column("id", sa.Integer(), nullable=False, comment="主键"),
        sa.Column(
            "created_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
            comment="创建时间",
        ),
        sa.Column(
            "updated_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="更新时间",
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=True, comment="逻辑删除"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "visitor_id", "request_id", name="uq_attempt_visitor_request"
        ),
    )
    op.create_index(
        "idx_ea_created_time", "exercise_attempts", ["created_time"], unique=False
    )
    op.create_index(
        "idx_ea_visitor_exercise",
        "exercise_attempts",
        ["visitor_id", "exercise_id"],
        unique=False,
    )
    op.create_index(
        "idx_ea_visitor_lesson",
        "exercise_attempts",
        ["visitor_id", "lesson_slug"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exercise_attempts_id"), "exercise_attempts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_exercise_attempts_visitor_id"),
        "exercise_attempts",
        ["visitor_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_exercise_attempts_visitor_id"), table_name="exercise_attempts"
    )
    op.drop_index(op.f("ix_exercise_attempts_id"), table_name="exercise_attempts")
    op.drop_index("idx_ea_visitor_lesson", table_name="exercise_attempts")
    op.drop_index("idx_ea_visitor_exercise", table_name="exercise_attempts")
    op.drop_index("idx_ea_created_time", table_name="exercise_attempts")
    op.drop_table("exercise_attempts")
    # ### end Alembic commands ###
