"""add_analytics_tables

Revision ID: 92845c146ce6
Revises: 
Create Date: 2026-05-29 19:53:25.625675
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '92845c146ce6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_snapshots',
    sa.Column('visitor_id', sa.String(length=64), nullable=False, comment='访客 ID'),
    sa.Column('lesson_slug', sa.String(length=128), nullable=True, comment='关联课程 slug'),
    sa.Column('code', sa.Text(), nullable=False, comment='代码内容'),
    sa.Column('language', sa.String(length=16), nullable=True, comment='代码语言'),
    sa.Column('version', sa.Integer(), nullable=True, comment='版本号'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='快照描述'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cs_visitor_lesson', 'code_snapshots', ['visitor_id', 'lesson_slug'], unique=False)
    op.create_index(op.f('ix_code_snapshots_id'), 'code_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_code_snapshots_visitor_id'), 'code_snapshots', ['visitor_id'], unique=False)
    op.create_table('daily_stats',
    sa.Column('stat_date', sa.String(length=10), nullable=False, comment='日期 YYYY-MM-DD'),
    sa.Column('active_users', sa.Integer(), nullable=True, comment='当日活跃用户数'),
    sa.Column('new_users', sa.Integer(), nullable=True, comment='当日新增用户数'),
    sa.Column('code_runs', sa.Integer(), nullable=True, comment='代码运行次数'),
    sa.Column('lessons_completed', sa.Integer(), nullable=True, comment='课程完成次数'),
    sa.Column('ai_helps', sa.Integer(), nullable=True, comment='AI 助手使用次数'),
    sa.Column('avg_session_minutes', sa.Float(), nullable=True, comment='平均学习时长（分钟）'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_stats_id'), 'daily_stats', ['id'], unique=False)
    op.create_index(op.f('ix_daily_stats_stat_date'), 'daily_stats', ['stat_date'], unique=True)
    op.create_table('learning_records',
    sa.Column('visitor_id', sa.String(length=64), nullable=False, comment='访客 ID（前端生成）'),
    sa.Column('event_type', sa.String(length=32), nullable=False, comment='事件类型: code_run / code_save / lesson_complete / ai_help / lesson_start'),
    sa.Column('lesson_slug', sa.String(length=128), nullable=True, comment='关联课程 slug，全局事件可为空'),
    sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='持续时长（秒），如课程阅读时长'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lr_created_time', 'learning_records', ['created_time'], unique=False)
    op.create_index('idx_lr_lesson_slug', 'learning_records', ['lesson_slug'], unique=False)
    op.create_index('idx_lr_visitor_event', 'learning_records', ['visitor_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_learning_records_id'), 'learning_records', ['id'], unique=False)
    op.create_index(op.f('ix_learning_records_visitor_id'), 'learning_records', ['visitor_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('visitor_id', sa.String(length=64), nullable=False, comment='访客 ID'),
    sa.Column('total_learning_minutes', sa.Integer(), nullable=True, comment='累计学习时长（分钟）'),
    sa.Column('lessons_completed', sa.Integer(), nullable=True, comment='已完成课程数'),
    sa.Column('code_runs', sa.Integer(), nullable=True, comment='代码运行次数'),
    sa.Column('ai_helps', sa.Integer(), nullable=True, comment='AI 助手使用次数'),
    sa.Column('current_streak', sa.Integer(), nullable=True, comment='当前连续学习天数'),
    sa.Column('longest_streak', sa.Integer(), nullable=True, comment='最长连续学习天数'),
    sa.Column('last_active_date', sa.String(length=10), nullable=True, comment='最后活跃日期 YYYY-MM-DD'),
    sa.Column('polars_score', sa.Float(), nullable=True, comment='Polars 能力分 (0-100)'),
    sa.Column('duckdb_score', sa.Float(), nullable=True, comment='DuckDB 能力分 (0-100)'),
    sa.Column('sql_score', sa.Float(), nullable=True, comment='SQL 能力分 (0-100)'),
    sa.Column('data_processing_score', sa.Float(), nullable=True, comment='数据处理能力分 (0-100)'),
    sa.Column('api_mastery_score', sa.Float(), nullable=True, comment='API 熟练度分 (0-100)'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_visitor_id'), 'user_profiles', ['visitor_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_visitor_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_learning_records_visitor_id'), table_name='learning_records')
    op.drop_index(op.f('ix_learning_records_id'), table_name='learning_records')
    op.drop_index('idx_lr_visitor_event', table_name='learning_records')
    op.drop_index('idx_lr_lesson_slug', table_name='learning_records')
    op.drop_index('idx_lr_created_time', table_name='learning_records')
    op.drop_table('learning_records')
    op.drop_index(op.f('ix_daily_stats_stat_date'), table_name='daily_stats')
    op.drop_index(op.f('ix_daily_stats_id'), table_name='daily_stats')
    op.drop_table('daily_stats')
    op.drop_index(op.f('ix_code_snapshots_visitor_id'), table_name='code_snapshots')
    op.drop_index(op.f('ix_code_snapshots_id'), table_name='code_snapshots')
    op.drop_index('idx_cs_visitor_lesson', table_name='code_snapshots')
    op.drop_table('code_snapshots')
    # ### end Alembic commands ###
